### ISSUE TITLE
Merged BAM from TopHat2

### ISSUE THREAD

**Issue by jasonwalker80** [ChrisMaherLab/INTEGRATE#2]
@jin-wash-u 

Is there a way to provide a combined, merged BAM file with both mapped and unmapped reads from TopHat2?  Or do I need to split the mapped and unmapped before running Integrate?

**Comment by jin-wash-u** [comment]
INTEGRATE can handle both merged file and split files:

Integrate fusion reference.fasta annot.txt ./bwts **merged.bam merged.bam** dna.tumor.bam dna.normal.bam

or

Integrate fusion reference.fasta annot.txt ./bwts **accepted_hits.bam unmapped.bam** dna.tumor.bam dna.normal.bam

where merged.bam is merged from accepted_hits.bam unmapped.bam.
